-- Sync DRE categories with new classification rules

delete from public.dre_categories;

insert into public.dre_categories (type, category, subcategory, display_order) values
-- Receitas
('RECEITA', 'Mensalidades', 'Alunos', 1),
('RECEITA', 'Mensalidades', 'Fretamento', 2),
('RECEITA', 'Viagens Extras', null, 3),

-- Custos
('CUSTO', 'Motoristas', 'Sal?rio', 10),
('CUSTO', 'Motoristas', 'Di?rias', 11),
('CUSTO', 'Motoristas', 'Horas extras', 12),
('CUSTO', 'Motoristas', 'Encargos trabalhistas (INSS, FGTS)', 13),
('CUSTO', 'Motoristas', 'F?rias + 1/3', 14),
('CUSTO', 'Motoristas', '13? sal?rio', 15),
('CUSTO', 'Motoristas', 'Rescis?es', 16),
('CUSTO', 'Combust?vel', 'Diesel', 20),
('CUSTO', 'Combust?vel', 'Aditivos', 21),
('CUSTO', 'Combust?vel', 'ARLA 32', 22),
('CUSTO', 'Manuten??o de Ve?culos', 'Pe?as', 30),
('CUSTO', 'Manuten??o de Ve?culos', 'M?o de obra mec?nica', 31),
('CUSTO', 'Manuten??o de Ve?culos', 'Troca de ?leo', 32),
('CUSTO', 'Manuten??o de Ve?culos', 'Filtros', 33),
('CUSTO', 'Manuten??o de Ve?culos', 'Pneus', 34),
('CUSTO', 'Manuten??o de Ve?culos', 'Alinhamento e balanceamento', 35),
('CUSTO', 'Manuten??o de Ve?culos', 'Lavagem', 36),
('CUSTO', 'Manuten??o de Ve?culos', 'Manuten??o preventiva', 37),
('CUSTO', 'Manuten??o de Ve?culos', 'Manuten??o corretiva', 38),
('CUSTO', 'Documenta??o e Regulariza??o', 'Licenciamento', 40),
('CUSTO', 'Documenta??o e Regulariza??o', 'IPVA', 41),
('CUSTO', 'Documenta??o e Regulariza??o', 'Vistoria', 42),
('CUSTO', 'Documenta??o e Regulariza??o', 'ANTT / Artesp', 43),
('CUSTO', 'Documenta??o e Regulariza??o', 'Tac?grafo (aferi??o)', 44),
('CUSTO', 'Documenta??o e Regulariza??o', 'Seguro obrigat?rio', 45),
('CUSTO', 'Seguros', 'Seguro do ve?culo', 50),
('CUSTO', 'Seguros', 'Seguro de passageiros', 51),
('CUSTO', 'Seguros', 'Seguro contra terceiros', 52),
('CUSTO', 'Deprecia??o', 'Deprecia??o dos ?nibus', 60),
('CUSTO', 'Deprecia??o', 'Deprecia??o de equipamentos (ex: c?meras)', 61),
('CUSTO', 'Ped?gios', 'Ped?gios fixos da rota', 70),
('CUSTO', 'Ped?gios', 'Ped?gios eventuais', 71),

-- Despesas
('DESPESA', 'Administrativo', 'Pr?-labore', 100),
('DESPESA', 'Administrativo', 'Sal?rio administrativo', 101),
('DESPESA', 'Administrativo', 'Encargos', 102),
('DESPESA', 'Administrativo', 'Contabilidade', 103),
('DESPESA', 'Administrativo', 'Honor?rios jur?dicos', 104),
('DESPESA', 'Administrativo', 'Sistema / Software', 105),
('DESPESA', 'Administrativo', 'Internet', 106),
('DESPESA', 'Administrativo', 'Energia el?trica', 107),
('DESPESA', 'Administrativo', 'Telefone', 108),
('DESPESA', 'Comercial', 'Marketing', 110),
('DESPESA', 'Comercial', 'Impulsionamento', 111),
('DESPESA', 'Comercial', 'Designer', 112),
('DESPESA', 'Comercial', 'Impressos', 113),
('DESPESA', 'Financeiro', 'Taxas banc?rias', 120),
('DESPESA', 'Financeiro', 'Juros', 121),
('DESPESA', 'Financeiro', 'Multas', 122),
('DESPESA', 'Financeiro', 'Tarifas de boleto / PIX', 123),
('DESPESA', 'Financeiro', 'Antecipa??o de receb?veis', 124),
('DESPESA', 'Estrutura F?sica', 'Aluguel (se houver)', 130),
('DESPESA', 'Estrutura F?sica', 'IPTU', 131),
('DESPESA', 'Estrutura F?sica', '?gua', 132),
('DESPESA', 'Estrutura F?sica', 'Manuten??o do escrit?rio', 133),
('DESPESA', 'Outros', 'Uniformes', 140),
('DESPESA', 'Outros', 'Treinamentos', 141),
('DESPESA', 'Outros', 'Multas de tr?nsito', 142),
('DESPESA', 'Outros', 'Brindes', 143);
